"""empty message

Revision ID: 840925816329
Revises: 3422ae422c63
Create Date: 2019-12-10 17:04:45.429305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840925816329'
down_revision = '3422ae422c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
